#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#AutoStart applications
sxhkd &
picom --config $HOME/.config/picom/picom.conf &
nitrogen --restore &
dunst &
polybar &

bspc rule -a "*" state=floating

bspc bind super+m node -m
bspc bind super+f node -g fullscreen on
bspc bind super+Shift+f node -g fullscreen off
bspc bind super+d rofi -show drun
bspc bind alt+Tab rofi -show window
